config/routes.rb
Rails.application.routes.draw do

  resources :obtain_coupons

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_for :accounts, controllers: {
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
  }
  root to: 'accounts/sessions#new'

namespace :api do
  namespace :v1 do
    resources :obtain_coupons
    resources :warehouses, except: [:new, :edit]
  end
end  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/obtain_coupon.rb
class ObtainCoupon < ApplicationRecord
  belongs_to :account
  belongs_to :obtain_catalogue
  belongs_to :coupon
end

app/controllers/api/v1/obtain_coupons_controller.rb
class Api::V1::ObtainCouponsController < ApplicationController
    before_action :authenticate_account!
    before_action :check_user_type, only: [:index, :new, :create, :destroy]
    def index 
      coupons= Coupon.all
      coupons_obtained_by_account = current_account.obtain_coupons
      response_data = {
              coupons: coupons,
              coupons_obtained_by_account: coupons_obtained_by_account
        }
      render json: response_data, status: :ok
    end   
    def new 
      obtain_coupon = ObtainCoupon.new
      render json: obtain_coupon, status: :ok
    end
    def create
      @obtain_coupon = ObtainCoupon.new(obtain_coupon_params)
      if @obtain_coupon.save
        render json: @obtain_coupon, status: :created
      else
      end
    end
    def destroy
      @obtain_coupon = ObtainCoupon.find(params[:id])
      @obtain_coupon.destroy
      render json: @obtain_coupon, status: :unprocessable_entity
    end
      private
      def obtain_coupon_params
        params.require(:obtain_coupon).permit(:coupon_id,:catalogue_id, :account_id)
      end
      def check_user_type
        if current_account && current_account.user_type == "seller"
        end
      end  
end

app/controllers/obtain_coupons_controller.rb
class ObtainCouponsController < ApplicationController
    before_action :authenticate_account!
    before_action :check_user_type, only: [:index, :new, :create, :destroy]
    def index 
        @coupons= Coupon.all
         @coupons_obtained_by_account = current_account.obtain_coupons
    end   
    def new 
        @obtain_coupon = ObtainCouponAssociation.new
    end
    def create
      @obtain_coupon = ObtainCouponAssociation.new(obtain_coupon_params)
      if @obtain_coupon.save
        redirect_to obtain_coupons_path, notice: 'ObtainCoupon was successfully created.'
      else
        render :new
      end
    end
    def destroy
      @obtain_coupon = ObtainCouponAssociation.find(params[:id])
      @obtain_coupon.destroy
      redirect_to obtain_coupons_url,status: :see_other
    end
      private
      def obtain_coupon_params
        params.require(:obtain_coupon_association).permit(:coupon_id,:catalogue_id, :account_id)
      end
      def check_user_type
        if current_account && current_account.user_type == "seller"
        else
          redirect_to root_path, notice: 'Access denied.'
      end
    end  
end

app/helpers/api/v1/obtain_coupons_helper.rb
module Api::V1::ObtainCouponsHelper
end

app/helpers/obtain_coupons_helper.rb
module ObtainCouponsHelper
end

app/views/obtain_coupons/index.html.erb
<%= render '/navbar' %>
<div class="main">
<div class="first">

<h1>All Coupons </h1>
<% @coupons.each do |coupon| %>
    <%= coupon.id %> 
    <%= coupon.name %>    
    <%= coupon.discount %>       
    <%= coupon.coupon_code %>
    <%= coupon.start_date %>
    <%= coupon.end_date %>                 
  <br><%end%> 
</div>
<div class="first">
  <h1>obtained coupon</h1>
  <% @coupons_obtained_by_account.each do |obtained_coupon| %>
    <%= obtained_coupon.id %> 
      <%= obtained_coupon.id %>    
      
      <%= link_to "Delete", obtain_coupon_path(obtained_coupon), class: "btn btn-danger btn-sm", data: { turbo_method: :delete, turbo_confirm: "are you sure?" } %>
      <br>
  <% end %>
  </div>
  <div class="first">
  <h1>obtained catalogue</h1>
  <% @coupons_obtained_by_account.each do |obtained_coupon| %>
  <%= obtained_coupon.catalogue.name %> 
  <%end%>
</div>
  </div>
  <div class="create-button">
    <%= link_to 'new obtain coupon', new_obtain_coupon_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/obtain_coupons/new.html.erb
<%# <%= form_with(model: [:obtain_coupons, @new_coupons], local: true) do |form| %> 
<%= form_with(model: @obtain_coupon, url: obtain_coupons_path, local: true) do |form| %>
  <div>
    <div>
      <%= form.label :coupon_id, 'Select Coupon:' %>
      <%= form.collection_select :coupon_id, Coupon.all, :id, :name, prompt: 'Select a coupon' %>
    </div>
     <div>
      <%= form.label :catalogue_id, 'Select Catalogue:' %>
      <%= form.collection_select :catalogue_id, Catalogue.all, :id, :name, prompt: 'Select a catalogue' %>
    </div>

    <div>
      <%= form.label :account_id, 'Account ID (hidden):' %>
      <%= form.hidden_field :account_id, value: current_account.id %>
    </div>
  </div>

  <%= form.submit 'Submit' %>
<% end %>